jmUtil={Enuu:function(j,g){if(g===undefined)g=true;var _t=(j instanceof Array)?"array":(typeof j);if(typeof j==="number"&&String(j).length>10){_t="string";j=String(j);}
switch(_t){case"string":return g?this.a(j):this.e(j);break;case"array":return this.r(j,g);break;case"number":return g?Number(this.a(String(j))):Number(this.e(String(j)));break;default:return this.o(j,g);break;}},o:function(b,l){var _j={};for(var a in b){if(!b.hasOwnProperty(a))continue;_j[a]=this.Enuu(b[a],l);}
return _j;},r:function(t,b){var _r=[];t.map(a=>{a=this.Enuu(a,b);_r.push(a);})
return _r;},a:function(u){var d=[],c='',a='';if(typeof u==="string"){u=u.split('');}
for(var i=0,w=u.length;i<w;i++){c=u[i];a=encodeURIComponent(c);if(a==c){if(typeof c==="string"){a=c.charCodeAt().toString(16);}
a=('00'+a).slice(-2);}
d.push(a);}
return d.join('').replace(/%/g,'').toUpperCase();},e:function(c){for(var i=0,e=c.length,v="%";i<e;i++){v+=c[i];if(i%2==1)v+='%';}
v=v.substring(0,v.length-1);return decodeURIComponent(v);},b:function(){var u=navigator.userAgent,app=navigator.appVersion;return{trident:u.indexOf('Trident')>-1,presto:u.indexOf('Presto')>-1,webKit:u.indexOf('AppleWebKit')>-1,gecko:u.indexOf('Gecko')>-1&&u.indexOf('KHTML')==-1,iOS:!!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/),android:u.indexOf('Android')>-1||u.indexOf('Adr')>-1,iPhone:u.indexOf('iPhone')>-1,iPad:u.indexOf('iPad')>-1,webApp:u.indexOf('Safari')==-1,weixin:u.indexOf('MicroMessenger')>-1,qq:u.match(/\sQQ/i)==" qq"};}(),d:function(){return(window.screen.width+" * "+window.screen.height);},v:function(){var r=this.b,a;for(var i in r){if(!r.hasOwnProperty(i))continue;if(r[i]){a=i;}}
return a;},n:function(y){switch(y){case"trident":return 1;break;case"presto":return 2;break;case"webKit":return 3;break;case"gecko":return 4;break;case"mobile":return 5;break;case"iOS":return 6;break;case"android":return 7;break;case"iPhone":return 8
break;case"iPad":return 9;break;case"webApp":return 10;break;case"weixin":return 11;break;default:return 12;break;}},w:function(){var sUserAgent=navigator.userAgent;var isWin=(navigator.platform=="Win32")||(navigator.platform=="Windows");var isMac=(navigator.platform=="Mac68K")||(navigator.platform=="MacPPC")||(navigator.platform=="Macintosh")||(navigator.platform=="MacIntel");if(isMac)return"Mac";var isUnix=(navigator.platform=="X11")&&!isWin&&!isMac;if(isUnix)return"Unix";var isLinux=(String(navigator.platform).indexOf("Linux")>-1);if(isLinux)return"Linux";if(isWin){var isWin2K=sUserAgent.indexOf("Windows NT 5.0")>-1||sUserAgent.indexOf("Windows 2000")>-1;if(isWin2K)return"Win2000";var isWinXP=sUserAgent.indexOf("Windows NT 5.1")>-1||sUserAgent.indexOf("Windows XP")>-1;if(isWinXP)return"WinXP";var isWin2003=sUserAgent.indexOf("Windows NT 5.2")>-1||sUserAgent.indexOf("Windows 2003")>-1;if(isWin2003)return"Win2003";var isWinVista=sUserAgent.indexOf("Windows NT 6.0")>-1||sUserAgent.indexOf("Windows Vista")>-1;if(isWinVista)return"WinVista";var isWin7=sUserAgent.indexOf("Windows NT 6.1")>-1||sUserAgent.indexOf("Windows 7")>-1;if(isWin7)return"Win7";}
return"other";},getData:function(){var g=this.d()+","+this.n(this.v())+","+this.w();return this.Enuu(g);}}